name: node js practice

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '18.20.2'

jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: 'npm'

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present